package euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author rajan-c
 *
 */
public class Problem2 {
	private static long sumOfEvenFibonacciTerms(long upperLimit) {
		long prev2 = 0, prev1 = 1, current = prev2 + prev1, sum = 0;
		while (current < upperLimit) {
			if ((current & 1) == 0)
				sum += current;
			prev2 = prev1;
			prev1 = current;
			current = prev1 + prev2;
		}
		return sum;
	}

	public static void main(String[] args) {
		System.out.println(sumOfEvenFibonacciTerms(4000000));
	}
}
