package arrays;

import java.util.HashMap;
import java.util.Map;

public class TeamRanking {
	public static String rankTeams(String[] votes) {
		if (votes.length == 1 || votes[0].length() == 1) {
			return votes[0];
		}
		Map<Character, Integer> map = new HashMap<>();
		int teams = votes[0].length();

		for (String vote : votes) {
			for (int teamSize = 0; teamSize < teams; teamSize++) {
				map.putIfAbsent(vote.charAt(teamSize), 0);
				map.put(vote.charAt(teamSize), map.get(vote.charAt(teamSize)) + teamSize + 1);
			}
		}

		int size = map.size();
		StringBuilder order = new StringBuilder();
		while (size > 0) {
			char maxKey = getMax(map);
			order.append(maxKey);
			size--;
			map.remove(maxKey);
		}
		return order.toString();
	}

	public static char getMax(Map<Character, Integer> map) {
		char max = '\0';
		int maxNumber = Integer.MAX_VALUE;
		for (Map.Entry<Character, Integer> entry : map.entrySet()) {
			if (maxNumber > entry.getValue()) {
				max = entry.getKey();
				maxNumber = entry.getValue();
			} else if (maxNumber == entry.getValue() && max > entry.getKey()) {
				max = entry.getKey();
			}
		}
		return max;
	}

	public static void main(String[] args) {
//		System.out.println(rankTeams(new String[] { "BCA", "CAB", "CBA", "ABC", "ACB", "BAC" }));
//		System.out.println(rankTeams(new String[] { "WXYZ", "XYZW" }));
//		System.out.println(rankTeams(new String[] { "ZMNAGUEDSJYLBOPHRQICWFXTVK" }));
//		System.out.println(rankTeams(new String[] { "ABC", "ACB", "ABC", "ACB", "ACB" }));

		System.out.println(rankTeams(new String[] { "PGAOFXIKYJVSLTUHCZQRE", "LSIAPTHYCGURKEZXJOFQV",
				"UGSARZICOXYPHTQFJKVEL", "XIAOKSVGRJCHQZUETLYPF", "OHRXPGEVUYCSKZILQATFJ", "UHFSCZVKIELGOQJYRXPAT",
				"QECXVZKJTLIYHUFRGOSAP", "RJGAZIKPEVUSTOXFQYCHL", "XRFGPAQSJOETHVCZIKLUY", "ZCTQOVRFKXJGEALSHIYUP",
				"QGTEHXCJRIPSUZALOYFVK", "GIHXVJPQYOSZFRKLEUTAC", "LURXHFECKZSYPTQGAOJVI", "TFUKZELVARQCXIYPJHGSO",
				"FIPYTACSXZKLRGOHJVEQU", "ZKJQOGHVURAISXFLPYECT", "XKOJAHVQUCETFPRYZGLSI", "TUKZAVIFXEGQCSOLJRPHY",
				"OSIPCFVRLAYKEHZTJGUQX", "OYAQTCEKLGPRZVISUXFHJ", "SKHCXEZLTFVQOIUPRAJGY", "CRZPAEILFTOKUJVGXHQYS",
				"OQVLPEYZFIGJRKUSXAHTC", "VQTXURZKAPGHEIFCOLSJY", "YVRZKXSOAEIPUQJHGCFLT", "YEJTGFQPOZLCARSUIKVHX",
				"XKASIECRHVQFPULZTOGJY", "KAQVYSZLTFXCGEJIRUHOP", "IYJXCUTOAPQKHEZFGRVSL", "OIEPRLZGUVQHSYJAFTXCK",
				"CIGVAZLKORXQYPHTEUSFJ", "UVTCJFQOGXIZHLKYRASEP", "FCVOYSJHZLKATXRIUPQGE", "TJLQFSRKIUGPCVZHOEAXY",
				"FUHLSRGTCOXAEZVQIYKPJ", "CAGRHEUQZISYKXLFVPJOT", "LASKUHEPJQXRCTZOVIYFG", "IGKJSYLVFCUXETRAHZQPO",
				"UZGXPIAFVOSLKRYQJTCHE", "VKELXAFPOGSRIZCUQYTHJ", "GCTJEUFRVLKAIOYSHZXQP", "PHUOAXLYFTCRSEQIKGJZV",
				"XLQYSIJHTREFPOKCUGVAZ", "LUZXHQKIATOCGJYPFSVRE", "XILVQZAFUKECYJGTPHSOR", "GCQFHJKTAERVPIYUSZOLX",
				"ZPRILGHYXTFVSQCAUKEOJ", "SLFTYQPZKUAIVGRHEOCXJ", "FCUVEOKHGZQSYJRXPAILT", "AKZJRQCPVHYGSXLFITUOE",
				"OKVEHCXPYRUGIAZJQFSLT", "YZVHPIGSLREJQCXOKFATU", "QTCILUZFVYHSAPGJEKXRO", "YXKJOPHIVGARUTZEFLSCQ",
				"OZPXURLHEKFQTSIVJYGCA", "YIVEGRJLTPOAZFCQSUXHK", "VPQUXLYGACSITFKEJHORZ", "AOEQLYPFZUXCKHSTVIJRG",
				"IFYTULEXKZRCOHASQPJGV", "TASULVYKZPOCGIHJERXFQ", "RGXYZCHVEAPTJISQUFKOL", "XKVRTHJSLOZPIAYUEQGFC",
				"EYIRXQTCUPHSVJFZLAKOG", "ZRJSTQIGPELKUCHAOYVFX", "EIXJPTZGRKVYCUFAOHQLS", "LRSGUJZYXCIVQOAHTFPEK",
				"ZHLOESVGIARXCUQYKPFJT", "ZKQLVGOIFASTPUHYJRCXE", "ZLPJQYTXEGAFHOSRCIUVK", "ZVHYQJXCGTAFKLEISOPUR",
				"KZGLYEQAURFHSXIVPTJCO", "TIXPAYEKJLVGCQRUHOSZF", "ESORYCVXLPKZFQJAUGIHT", "FAJTCHORZGLIKXYSVUPQE",
				"AOXHJEZFYLIQCPRVTSGKU", "IZVAPOTEHCJQLKRGFUSXY", "RTVYZHSIPGCEKJQUAXFOL", "GSHOKEXAZCIQYTRJFVLPU",
				"SXZLKIUGEVCPFHTQJARYO", "QPCOTHISGLKYJFUAZXVRE", "XPUEYATJHCOLVGSQRIZKF", "GIKSZFHEQLTCVXJAYOPUR",
				"RFSOEJPUAGKYHZIQCTLXV", "UFHXJLITQPEGCKOSZYRAV", "ZVQAFGXEIRSTPJYLHCOKU", "ZITVJLSOAUGPCFYXHRQKE",
				"RCZOIPEXFJAQGSYVLKHUT", "TUHVJROCXIGEPLQAZYKSF", "ATQJGKUIPLZXEYCRSOVFH", "TVHYLSRAKIXJFGEPOZUCQ",
				"CAPHZLGXQSIRTJYFOKEVU", "FAYOKHEUZIRJXQTVGCSPL", "IJCRUHVAPFYKGXLTSOQEZ", "ZKIJLQEAUVHFTYRXCSGOP",
				"ALFTJSRXUQPIOVZCYHEKG", "ZASIVJQYUCRPEKGLTXFHO", "OICQXZPEFUSTVALKGYRJH", "ZOKVPHUXGRQIJCSEYALFT",
				"FKACPHOSIREGUTYLJXZVQ", "IZXOREFGSLPKUHAYCVTJQ", "UVXZTCFAQEYLORSKHPJIG", "PKVQCYSTLHRZIFAUEXJGO",
				"IRFZSKGEHQVOLXCTJUPAY", "XYHPVOTILEAUZJGSKQCRF", "ERXJLFZQIGHPCSTYKUVOA", "SZTIFCGVEKUJYPAOQXHRL",
				"JPTGQOEYFIKURCVHXALZS", "URJGTXZKICAOQSLVEYHFP", "ZERGKOLTSUIXJFACVQHPY", "GQCVAJYIKRZLTPSFHOUEX",
				"OKRCTSGLZXQJEHPFVYUIA", "GUKXARTQFYSCVEZIOJHLP", "UTCIRLFHGJOSYZVPQKEAX", "JPIOVSFZHUTQKCERXAGLY",
				"LKJEGOHRTYQFXUSCVIPZA", "LSETPUAHZYOICVRGJFXKQ", "OPGHRVUXQEYLZFISTJKCA", "VOKCSGFTXZEIRYALHJPQU",
				"POTXFYCQIVZHLGJERAUSK", "FAUIECXOYPLRHJKTSZQVG", "XFAETYRCJUGVPQZOKSLHI", "LGCVYIAZRFJSHQXTKUOPE",
				"YKATQFIURCHPLSVGJEXOZ", "IRUHTAXVYZKFPSEOJCLGQ", "TAVEXIHLPOGSZRCJFQKUY", "GFACLJSETKIXRZUYHVPOQ",
				"XTJKSAZIQYRCLPGOHUFEV", "GSFTZLJCVKRYUOXAQIEPH", "GIOLPRXHCSUFKAVTJZEQY", "SFCRPVGYKOUZJALQEXHIT",
				"EUTOKQGFCLRAVZPJYSXHI", "UOYSHGLTPZXRICFJEKAVQ", "OTZIGVXSQHCPRYUKELAJF", "SGZOEHLKYUPXCJRFTAVQI",
				"JOCVZLGSUIAHPFKYTQERX", "ZFSRJULQGKIOXEPYHTACV", "FGSJCIYXHEAZTOLUKRVQP", "YXHICZVFTSQJKLPOURGAE",
				"XALRUOHJZYVEGQPKCSFIT", "KCIJLRXYHAESGFQUOPVZT", "AUTSXLECOGPZIHRVYQKFJ", "GIZRAKEVOXLTCJSUHQPFY",
				"ZKUPCORTFYEIAGJQXVLHS", "JALHXZQIYSUROPCEGKVFT", "KUIGTSQAJEOZYPCFHLXRV", "LXICRFZJEUVYASPKQHTOG",
				"EFUPZKRXLCAVJGQITHOSY", "EUYGQKARZJVHLIPFCOSTX", "AOXTKHRYLJZQEUCSPGVIF", "SHUTLZEGRJYPCVAFXQOKI",
				"GUZTAXQLKIRFYEOHJSPVC", "RGOZPAXLYVJSHFICKTQUE", "ASCHFQVTRLEKYUZIXGJPO", "CQFRUSIXLOZPVJTGYAHEK",
				"VGYURSHEXIKCFOAPTQLJZ", "VFQCGPEAYISTXKORLUJHZ", "UZJOYGVRETFSPLQAIKHCX", "JKQRZFXICESTHPGOUYVAL",
				"XGFYRJKCVTESZPHLQUIOA", "YEPGFRALQOKJTXSZCIUVH", "CXHPFAYKVZQORLJUTEGSI", "PXHACSGJUILTYVQRFKEOZ",
				"RSILHFAYCQJKVUGZTPXOE", "IKAEOXFVPHSLRCQGZYJTU", "GVKRJFLXZUOSAEIYPTCQH", "TEXZOUVPICHGFLRYSQKAJ",
				"JCEHLTRZQVFOPUSIKGYXA", "GFLJHYXEAQTOPSKIUZVRC", "ZGKJFVEAUHIXRTCLSPYQO", "GXOTELHIQKUAFSVRPZYCJ",
				"XRZEUGOIVAKSYPHJQCFLT", "PYQVXGHSAKLRFTEZOUICJ", "QGHOCVKFEPUTSRAIJYZLX", "YRQVOLKJGFIXHEPCTUAZS",
				"CTXYFQVZASEHPIOUJGRLK", "GIZHRVQLJEYAKTSUCOPXF", "XIGKSCLTRYJHZFUOQAPVE", "RYCXPSEGIFAULKZTQJVHO",
				"PXEQTGYSHICLAVRUZKJOF", "AERXGTIHLUZSFKQYVPCJO", "SKTPVFXILUZHYCEJAQROG", "OCQUZKSJYLIVARFEHTPGX",
				"ISZXFQUKHJOTCREPGYALV", "LOSTQCIRZFVGYKPEAJHUX", "QPFTRGUKOIVXESYCJZLAH", "PXSUEIVOHZCKJFQLTGRAY",
				"QYLRCVJOPEXGUTZKSAIFH", "RJQPOFKXIHUZYVETCSLAG", "HTFJEAISYQZUXLCGVPORK", "ECGFLAHQJPORITXYUKVZS",
				"FJGAIOSPTVXUZYHLQKERC", "GEQLKYPICTUAFRSOVXZHJ", "CGJHEZKSTIUQOFVRYXLAP", "XYJSGTIKOVUFERLHCPAQZ",
				"LQFVECITUGXHOYJKASRZP", "HYGJQFUPZVORSKICLETXA", "ACTXZRUYPOJLIEFSKQVGH", "PHOLYCFUKRASEGTVQZXIJ",
				"RTUOEZHPSKAFXLQYICVGJ", "RAPTGQIJOSEFZUKVXCLHY", "EUAKTQLJFOHCPSYVGRZXI", "TYUPHSXVEZKIFQACRLJGO",
				"ZHOEAIULSVJQKGRYFTXPC", "CPEUIGVRFSOZAKYHQLTJX", "ZCOEYRHVQFLSJIXUATGKP", "FGSCJZKUTRVOLEYHQIPAX",
				"SPKIGAUVQJXZYEHROCFTL", "ITQVPZLEOGJUHKXRYFASC", "GSAFTOHJQCYLUVPZEXRKI", "ZPFKXLUJSRCAHOGYTVIEQ",
				"QIFYPTAJELCSOXUKRZGVH", "JFGZCQAELXKOIUHYRSTVP", "TIGPACUOYZJHXKSVQEFRL", "EATKLFGOCZVQHXRYSJIPU",
				"SPOJYHVQXGZELUACKFITR", "YTVIQXEZUJRFGCOLKSAPH", "SPGHEQZJVXKIOAYLRUCFT", "RFXCSUZIJAQTELHKVPOGY",
				"PHXJESZRGFLKOAVIQUTYC", "GUYCOKILATEJZXHFPRSVQ", "GQTUFLAKCPVRYIOHXEZJS", "AYVCGFTIQKLZSXEPHRJUO",
				"EAXRUTPZVHCGLISYQFKOJ", "SUVFHQGRLXEZAYJTCIPKO", "PXKTOGRLHQAJFZCIYUSVE", "ZGXYPLOSRCTAVFEUIQKHJ",
				"OKEHXFQSIZGCRJLPATYUV", "YXQILGVKPJOUTAZRCSEHF", "TYQAGXSCZVKLJEOIHPURF", "ELAJZPXRIFQVSGKTOCUHY",
				"YIPXUJHGACTVQEKSOZRLF", "ZPAGUYLVSRCIKOJXFTEQH", "LYKIJURAEGVZSFPXHCOTQ", "EULYFIOJTGXZQCPARHKSV"

		}));
	}
}
